### ISSUE TITLE
Odometry shows snake-like path while car going straight.

### ISSUE THREAD

**Issue by OliverShaoPT** [GDUT-Kyle/faster_lio_sam#1]
faster_lio_sam:
![image](https://user-images.githubusercontent.com/37506826/177447705-4426c0e4-1a3b-480a-905a-19424749c762.png)

fast-lio2
![image](https://user-images.githubusercontent.com/37506826/177448032-0b1a1c03-b9b6-4356-8fc0-5a892cf001a9.png)

**Comment by GDUT-Kyle** [comment]
If it's convenient for you, could you use faster-lio for the experiment? 
Thank you very much for your valuable experimental data. I will verify and improve it as soon as possible.

**Comment by OliverShaoPT** [comment]
> If it's convenient for you, could you use faster-lio for the experiment? Thank you very much for your valuable experimental data. I will verify and improve it as soon as possible.

faster-lio:
![image](https://user-images.githubusercontent.com/37506826/177450224-0c6f5ec9-2fcc-40d9-9a19-188115169670.png)

Both faster-lio and fast-lio2 show straight path, the problem may be the fusion of IESKF and iVox?

**Comment by OliverShaoPT** [comment]
The avia build-in IMU miss the orientation information, will it be the reason of left-right swinging?
![image](https://user-images.githubusercontent.com/37506826/177451718-730af362-f84f-49ed-b0f8-7700154a6387.png)

**Comment by GDUT-Kyle** [comment]
> 
The problem should be here, my project needs IMU pose information during system initialization.

**Comment by OliverShaoPT** [comment]
> > 
> 
> The problem should be here, my project needs IMU pose information during system initialization.

Thanks a lot for your answer! In addition, I find "Extrinsics (RSLIDAR -> LIVOX)" in parameter.yaml, are you planning to develop mult-lidar system? If possible, could you kindly release the support of spinning lidar like Velodyne or RoboSense?

**Comment by GDUT-Kyle** [comment]
Yes, my initial goal is to develop a generic multi-LiDAR SLAM solution, and I will complete the system development and open source as soon as possible.

**Comment by OliverShaoPT** [comment]
> Yes, my initial goal is to develop a generic multi-LiDAR SLAM solution, and I will complete the system development and open source as soon as possible.

Waiting for your good news!
