### ISSUE TITLE
global map save？

### ISSUE THREAD

**Issue by germmyymh** [GDUT-Kyle/faster_lio_sam#11]
Your project is sound,
How do I save the global point cloud map?
Or what is the topic of publishing an optimized global map?

**Comment by GDUT-Kyle** [comment]
没有这个选项诶，我以前都是在rviz上缓存每一帧点云来可视化地图

**Comment by germmyymh** [comment]
> 没有这个选项诶，我以前都是在rviz上缓存每一帧点云来可视化地图

So how to operate the cache on rviz and save the point cloud map?
