### ISSUE TITLE
6轴IMU能否可以?

### ISSUE THREAD

**Issue by RtJinxuWang** [GDUT-Kyle/faster_lio_sam#3]
想问下必须要用9轴IMU是为什么

**Comment by GDUT-Kyle** [comment]
是这样的，我当初写的时候是希望用构建的地图反投影到WGS84，所以为了方便起见，就将建图原点的Z轴和当地重力方向对齐，所以就用了IMU输出的姿态信息，当然6轴也可以，参考LINS用加速计输出算一下pitch和roll就行。
