### ISSUE TITLE
imuBiasHandler函数中有bug？

### ISSUE THREAD

**Issue by LeeXujie** [GDUT-Kyle/faster_lio_sam#6]
回调函数imuBiasHandler里：
`gyrBias(i) = imuBiasMsg->data[3+i];`应该是`gyrBias(i) = imuBiasMsg->data[4+i];`吧？

**Comment by GDUT-Kyle** [comment]
感谢，确实如你所说！

> 回调函数imuBiasHandler里： `gyrBias(i) = imuBiasMsg->data[3+i];`应该是`gyrBias(i) = imuBiasMsg->data[4+i];`吧？

**Comment by LeeXujie** [comment]
ImageProjection.cpp里你没改过来哦
