### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by ye-tingfeng** [GDUT-Kyle/faster_lio_sam#8]
首先对广工的slam实力表示一如既往的钦佩，现在由两个小问题想请教一下
1.我看见poseOptimaization.cpp这个文件里面没有内容，是否后续还会更新？
2.同样涉及到1，没有发现回环的使用，那gtsam在里面是不是只起到对imu的预积分作用/
若能收到贵团队的回答，感激不尽

**Comment by GDUT-Kyle** [comment]
感谢你的关注。
1. 这个项目是我个人学习SLAM时的demo，poseOptimaization.cpp这个文件本来是打算加入回环，GNSS等外部观测构建位姿图优化，不过后面将其独立到一个简单的回环检测优化节点中[livox_backend](https://github.com/GDUT-Kyle/livox_backend)，可以直接集成到FAST-LIO2或者当前项目。
2. 确实gtsam里面只起到对imu的预积分作用，当时希望测试自己的猜想，尝试参考LIO-SAM用滑窗的方式估计IMU的bias。
